# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myWeather ' do
  use_frameworks!

pod 'Alamofire', '~> 4.6'
pod 'SwiftyJSON', '~> 4.0.0'
pod 'RealmSwift'
pod 'Firebase/Core', '4.9.0'
pod 'Firebase/Auth', '4.9.0'
pod 'Firebase/Database', '4.9.0'

end

target 'myWeatherWidget' do
  use_frameworks!

pod 'Alamofire', '~> 4.6'
pod 'SwiftyJSON', '~> 4.0.0'
pod 'RealmSwift'
pod 'Firebase/Core', '4.9.0'
pod 'Firebase/Auth', '4.9.0'
pod 'Firebase/Database', '4.9.0'

end
